### ISSUE TITLE
Icon is appearing filled in black

### ISSUE THREAD

**Issue by lukepighetti** [ilikerobots/fontello#10]
Here is an icon I have made. It is fill only.

<img width="562" alt="Screen Shot 2019-07-09 at 10 18 54 AM" src="https://user-images.githubusercontent.com/666539/60895713-1d4b0b80-a233-11e9-9bca-acd9950d1e30.png">

This is how it renders in Flutter.

![IMG_153F2F81D4EA-1](https://user-images.githubusercontent.com/666539/60895703-191eee00-a233-11e9-8bdb-9eeff873931b.jpeg)

Here is the SVG file.

[delete.svg.zip](https://github.com/ilikerobots/polyicon/files/3373399/delete.svg.zip)

Any idea where this issue lies?

**Comment by shinyford** [comment]
I've seen this problem a lot - basically, it's because Fluttericon (for very good reasons) doesn't understand the stroke and fill semantics of svg, and needs a compound path. (I think.)

I've found it useful to pass any SVGs through icomoon first (https://icomoon.io) which seems to be able to convert most SVG images into a compound path version ideal for FlutterIcon.

**Comment by lukepighetti** [comment]
Thanks for the help, I'll close this for now and reopen it if necessary!

**Comment by ilikerobots** [comment]
Thanks @shinyford !

**Comment by Citaborg** [comment]
I have the same issue. A lot og .svgs exported from Figma are rendered black.
This is however only when uploading to fluttericons from Windows 10 (tested: chrome, edge, firefox). Uploading the same .svg from a Mac (tested: safari, chrome, edge) it renders correctly. All tested browsers on both Mac and Windows render the .svg correctly when opened directly.

The deleted-icon in issue above shows the same behaviour. Works fine when uploaded from Mac, rendered black when uploaded from Windows 10.

Cheers,
Citaborg

**Comment by JavascriptMick** [comment]
I just ran into this in 2025! 
resolved it by using icomoon.io ... free plan allows you to upload svg and export ttf font including a dart Class so TBH, no real reason for me to use flutericon at all, sorry guys.
