### ISSUE TITLE
Communication problems on download

### ISSUE THREAD

**Issue by shinyford** [ilikerobots/fontello#11]
I'm seeing a huge number of communication problems when trying to download a fontset.

<img width="357" alt="Screenshot 2019-07-13 at 10 02 41" src="https://user-images.githubusercontent.com/3885/61169592-5e0a9380-a557-11e9-9326-3ec85bb59bf6.png">

No idea what the problem is - but happy to help if there's anything I can contribute.

Cheers

Nic

**Comment by ilikerobots** [comment]
Hm, I haven't seen this, but I'm not using the site so often myself.  Is it still happening?  Unfortunately I'm away for the next 3-4 weeks on a bike trip, but please follow up with any more info you may find and I'll take a look when I'm back.

**Comment by ilikerobots** [comment]
This doesn't seems to be a continuing issue
