### ISSUE TITLE
returning chinese character

### ISSUE THREAD

**Issue by mosleim** [ilikerobots/fontello#12]
my output code is look like this:
```
/// Flutter icons CustomIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData flow_tree = const IconData(0xe800, fontFamily: _kFontFam);
}
```

i use the icon with this:

`BottomNavigationBarItem(icon: Icon(CustomIcon.flow_tree)),`   
the outpus is not a `flow_tree` icon. but like a chinese font.

**Comment by mosleim** [comment]
solved!
need to stop and re-run.

**Comment by tommybuonomo** [comment]
For me, just the re-run didn't worked. I had to execute a `flutter build` and run again.

**Comment by mosleim** [comment]
@tommybuonomo sometimes it can't work for me either. Sometime need to uninstall(debug application on the phone) or just rebuild or just stop and rerun.

**Comment by talamaska** [comment]
I tried everything I just seeing chinese character of the meteo icons.
rebuild, flutter clean, restart machine uninstall the app from the phone, everything.

**Comment by nicolasvahidzein** [comment]
I'm seeing chinese characters as well, it makes no sense. Anyone have a solution?
