### ISSUE TITLE
Asset load error: "N.Wire" unavailable after asset load.

### ISSUE THREAD

**Issue by z3r0c00l-2k** [ilikerobots/fontello#14]
When assessing the website an alert is showing saying that "Asset load error: "N.Wire" unavailable after asset load." .

**Comment by idootop** [comment]
me too

**Comment by ilikerobots** [comment]
Is this still occurring?

**Comment by idootop** [comment]
> 
> 
> Is this still occurring?

Thanks. It works.
Actually, the problem was happend on Firefox, then I changed to Edge there's no problem.
Now, It works on Firefox too.
I don't know what caused this problem.
