### ISSUE TITLE
Icon doesn't render properly

### ISSUE THREAD

**Issue by lukepighetti** [ilikerobots/fontello#18]
Not sure if this is a `flutter` issue or a `polyicon` issue, but here we go. It appears to be filling where there is no fill. Asset was created in Affinity Designer and is a single SVG path element. Is there an appropriate way to create the SVG asset so it works as expected?

<img width="400" alt="Screen Shot 2020-02-21 at 12 30 07 PM" src="https://user-images.githubusercontent.com/666539/75056898-e5cd5e80-54a5-11ea-8535-b5fd23cc54a0.png">

<img width="123" alt="Screen Shot 2020-02-21 at 12 30 12 PM" src="https://user-images.githubusercontent.com/666539/75056902-e8c84f00-54a5-11ea-8ec3-d1d5c89c1e25.png">

<img width="468" alt="Screen Shot 2020-02-21 at 12 30 22 PM" src="https://user-images.githubusercontent.com/666539/75056925-ef56c680-54a5-11ea-83bb-3352a42e5b84.png">

[filter.svg.zip](https://github.com/ilikerobots/polyicon/files/4237278/filter.svg.zip)

**Comment by mbayou** [comment]
Hi,

**Comment by mbayou** [comment]
Hi,

I am experimenting the same issue, checking the ttf itself it seems like the icon isn't generated well. Here is how it looks on fluttericons:

**Comment by mbayou** [comment]
Hi,

You should have a look into this one: https://github.com/ilikerobots/polyicon/issues/10

**Comment by lukepighetti** [comment]
Funny, I open an issue about an issue I closed haha. Go figure.
