### ISSUE TITLE
Add Vaadin icons

### ISSUE THREAD

**Issue by jouni** [ilikerobots/fontello#2]
Would be great if you could add [Vaadin icons](https://vaadin.com/icons) to the collection as well.

You can find the SVG files from here: https://github.com/vaadin/vaadin-icons/tree/master/assets/svg

**Comment by ilikerobots** [comment]
Site gets < 15 sessions/month; so I'm thinking there's not much demand for these iconsets.  I'm probably not going to spend much more time on this.  If someone makes a PR, I'd be happy to include it though.

**Comment by jouni** [comment]
Sure, completely understandable. Thanks for taking the time answer 😊

Great app anyways! I won’t have time for a PR at the moment, but I’ll keep the possibility in mind. We are betting heavily on Polymer, and I would expect our internal projects to need this service next year at least.

**Comment by ilikerobots** [comment]
You must be most of those visits :smile:.  I was experimenting with Polymer in context of Dart; I switched over to Angular when it became clear that's the direction Dart is heading.  PolyIcon became a bit of on orphan for me, which I almost turned off.  I'll leave it on for you.  Regards from across the gulf!

**Comment by lukepighetti** [comment]
It might get < 15 sessions a month but I would argue that those sessions are critical for people. I know they are critical for me.

**Comment by shinyford** [comment]
Totally agree with Luke - FlutterIcon is a really important part of two separate live (well, soon to be live in one case) commercial products that I work on.

**Comment by ilikerobots** [comment]
Just to put everyone at ease: the <15 sessions/mo comment was about the polyicon branch, which was a similar project I made for making polymer iconsets.  Fluttericon get significantly more sessions, so it's not going anywhere. :)
