### ISSUE TITLE
HTTPS for fluttericon.com

### ISSUE THREAD

**Issue by jaydanurwin** [ilikerobots/fontello#25]
Are there any near-term plans to get fluttericon.com hosted through HTTPS? The obvious advantage would be security improvements but also the fact that Google demotes sites without HTTPS now.

I know this is sort of thing is all mainly handled internally but let me know if there is anything I/we the users of this awesome service can do to help get this resolved. Thank you!

**Comment by ilikerobots** [comment]
done!  Should have done it a long time ago ;)
