### ISSUE TITLE
Can we have dedicated package for this on (pub.dev)?

### ISSUE THREAD

**Issue by dungnv2602** [ilikerobots/fontello#27]
So today I have done porting all icons in fluttericon.com into a package and it took me quite amount of time. And the problem is if is any of them is updated in the future, I will have to do the process again. I thought if we have a dedicated package for all of them on pub.dev, that would be awesome and I really hope that I am the last one doing this boring porting process.

**Comment by ilikerobots** [comment]
Ok, sure. I'll put a package togther in the next day or two.

**Comment by ilikerobots** [comment]
Published.  https://pub.dev/packages/fluttericon
