### ISSUE TITLE
Config file not being imported

### ISSUE THREAD

**Issue by g123k** [ilikerobots/fontello#3]
Hello,

I have created a font with material icons and SVGs. The following config file was then generated : https://gist.github.com/g123k/04b856379fd41577ad8608fe66b5f195

However when I import the json in the website, nothing happens.

Is-there something wrong with this json file?

Thanks.

**Comment by ilikerobots** [comment]
I imported the same config file and it appears to all work fine; 48 material and 16 custom, so it appears the config file is not the problem.  Is the problem persisting?  Are there any errors reported in the browser console?

**Comment by g123k** [comment]
Hello,

Thanks for your answer. When retrying today, everything works fine 🤔 now.
Weird... I close the issue, but clearly yesterday no error was printed in the console.
