### ISSUE TITLE
RPG-Awesome font library

### ISSUE THREAD

**Issue by filiph** [ilikerobots/fontello#37]
This is only a half-serious request. I'd like to see if this is something worth considering. If people think it's a good idea, I can follow [the process](https://github.com/ilikerobots/polyicon/wiki/How-to-suggest-font-to-FlutterIcon#how-to-prepare-a-font-for-use-with-fontello) to prepare the font.

Name: RPG-Awesome
License: SIL OFL 1.1
Icon count: 495
Homepage: http://nagoshiashumari.github.io/Rpg-Awesome/
Source: https://github.com/nagoshiashumari/Rpg-Awesome

![Screen Shot 2020-05-12 at 11 15 01 AM](https://user-images.githubusercontent.com/919717/81730113-e7be1280-9441-11ea-90d2-780dd5f6fc0b.png)

CONs: 

* Some of the icons don't look good in a small (16x16px) size and are clearly meant to be used at larger sizes. This is to be expected, since there are icons with such non-standard meanings such as `ra-implosion` or `ra-fireball-sword`.
* Lower level of professionalism than what's currently available at fluttericons.com. There are icons such as `ra-turd`. And icons have a larger variance of style.

PROs:

* A wide variety of meanings not available from other icon sets: animals, electronics, dice, cards, plants, astrology symbols, swords, etc.
* Creative juice for weekend warriors such as myself, for prototyping, building bespoke TRPG tools, or pair-programming with kids.

**Comment by ilikerobots** [comment]
Love it!  I've had a dueling wizard app in by back pocket for ~15 years now.  Maybe I've just been waiting for Flutter and this iconset...

I have to update some other fonts in the next few days anyway, so I'll prep the font and install.

**Comment by ilikerobots** [comment]
Added the RPGAwesome set. Game on!
