### ISSUE TITLE
how can i get orignal svgs from fluttericon.com

### ISSUE THREAD

**Issue by Icyoung** [ilikerobots/fontello#43]
I can't find the button of download.
thanks for you reply.

**Comment by ilikerobots** [comment]
There is no direct way to download svg from fluttericon. If the original authors of the webpack have provided SVG, e.g. RPGAwesome, Entypo, etc, then you can likely find them by following the links to the font's website or github.

![Screenshot_font_links](https://user-images.githubusercontent.com/6736189/82640660-a5e85580-9c13-11ea-9371-04c07bd04bbc.png)

If the original authors have not provided SVG, then 
 a) you can check the fluttericon source: https://github.com/ilikerobots/polyicon/tree/fluttericon/src
 or 
 b) convert the ttf file to svg using fontforge or batik or another tool
