### ISSUE TITLE
Communication problems with very large icon set

### ISSUE THREAD

**Issue by polilluminato** [ilikerobots/fontello#46]
Hi everyone I'm trying to create a custom font with Flutter with 1600+ icon.

I already uploaded all the SVG on the [fluttericon.com](https://www.fluttericon.com/) website and I managed to download the `config.json` but when I tap on Download it gave me a communication error

![Schermata da 2020-07-09 07-18-41](https://user-images.githubusercontent.com/202140/87000061-720dc300-c1b4-11ea-8246-20b8cda886cf.png).

So I removed all the icons, reupload `config.json`, retried download but I got the same error.

I also tried to use fontello-cli like I found in the readme but with command

```
fontello-cli --config config.json --host https://fluttericon.com install
```

It gave me 

```
/usr/lib/node_modules/fontello-cli/lib/fontello.js:39
        throw error;
        ^

Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: fluttericon.com. is not in the cert's altnames: DNS:www.fluttericon.com
    at Object.checkServerIdentity (tls.js:287:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1496:27)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:921:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:695:12) {
  reason: "Host: fluttericon.com. is not in the cert's altnames: DNS:www.fluttericon.com",
  host: 'fluttericon.com',
  cert: {
    subject: [Object: null prototype] { CN: 'www.fluttericon.com' },
    issuer: [Object: null prototype] {
      C: 'US',
      O: "Let's Encrypt",
      CN: "Let's Encrypt Authority X3"
    },
    subjectaltname: 'DNS:www.fluttericon.com',
    infoAccess: [Object: null prototype] {
      'OCSP - URI': [Array],
      'CA Issuers - URI': [Array]
    },
    modulus: 'C6E52116C530D56CA1B3D76D2739DB34BDB553FC37F4F565630BD387868C1C865498C4EC96697B41CFA4A20994313729FD21A7D48C6C58B4504F8FEA61A4ADCEDF422DA33A5863C3D5B4E56078DF1315461DC1EC2D855C779B9BEBAB3E44AF9493CB9A181A894893B0A810014FC8B4B64DF35CE4CAC21A148B91255AD10478D19E063227B793A0B2F907BDA9B730564D10D6052D3D87CC78A03D63E7AE3308615D35B8EE2BD0FB5B51D453751BA7683DF90F98E34D7AA991CC707ACAC9C69087955C39F24BED195F739704B0EF6EC0994557D720F72CC3CC9CFF9B97E923B5A70E63B4466015B0BAF2FA7D39D6B4CA33C1B58A5CB82C897544252E9365AC80CB',
    bits: 2048,
    exponent: '0x10001',
    pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 c6 e5 21 16 c5 30 d5 6c a1 b3 d7 6d 27 39 db 34 bd ... 244 more bytes>,
    valid_from: 'Jun  4 08:08:15 2020 GMT',
    valid_to: 'Sep  2 08:08:15 2020 GMT',
    fingerprint: 'A4:C2:0A:67:2D:5A:F8:80:E8:A8:A0:37:3E:96:2D:4B:3B:52:FE:61',
    fingerprint256: '89:EC:BA:28:35:01:FC:99:57:67:7F:58:13:1E:40:42:F9:86:C0:64:1C:C9:F3:88:2B:BC:AB:3B:00:C1:81:99',
    ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
    serialNumber: '03110463E07F25E2E352C07AFF3F30C245B6',
    raw: <Buffer 30 82 05 5c 30 82 04 44 a0 03 02 01 02 02 12 03 11 04 63 e0 7f 25 e2 e3 52 c0 7a ff 3f 30 c2 45 b6 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 4a ... 1326 more bytes>,
    issuerCertificate: {
      subject: [Object: null prototype],
      issuer: [Object: null prototype],
      infoAccess: [Object: null prototype],
      modulus: '9CD30CF05AE52E47B7725D3783B3686330EAD735261925E1BDBE35F170922FB7B84B4105ABA99E350858ECB12AC468870BA3E375E4E6F3A76271BA7981601FD7919A9FF3D0786771C8690E9591CFFEE699E9603C48CC7ECA4D7712249D471B5AEBB9EC1E37001C9CAC7BA705EACE4AEBBD41E53698B9CBFD6D3C9668DF232A42900C867467C87FA59AB8526114133F65E98287CBDBFA0E56F68689F3853F9786AFB0DC1AEF6B0D95167DC42BA065B299043675806BAC4AF31B9049782FA2964F2A20252904C674C0D031CD8F31389516BAA833B843F1B11FC3307FA27931133D2D36F8E3FCF2336AB93931C5AFC48D0D1D641633AAFA8429B6D40BC0D87DC393',
      bits: 2048,
      exponent: '0x10001',
      pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 9c d3 0c f0 5a e5 2e 47 b7 72 5d 37 83 b3 68 63 30 ... 244 more bytes>,
      valid_from: 'Mar 17 16:40:46 2016 GMT',
      valid_to: 'Mar 17 16:40:46 2021 GMT',
      fingerprint: 'E6:A3:B4:5B:06:2D:50:9B:33:82:28:2D:19:6E:FE:97:D5:95:6C:CB',
      fingerprint256: '25:84:7D:66:8E:B4:F0:4F:DD:40:B1:2B:6B:07:40:C5:67:DA:7D:02:43:08:EB:6C:2C:96:FE:41:D9:DE:21:8D',
      serialNumber: '0A0141420000015385736A0B85ECA708',
      raw: <Buffer 30 82 04 92 30 82 03 7a a0 03 02 01 02 02 10 0a 01 41 42 00 00 01 53 85 73 6a 0b 85 ec a7 08 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 3f 31 24 ... 1124 more bytes>,
      issuerCertificate: [Object]
    }
  },
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}

```

How can I solve this issue and create my custom font?

**Comment by polilluminato** [comment]
I managed to solve my own issue by breaking all the icons in 7 chunks, generate 7 different .ttf and merge by hand all the 7 classes that [fluttericon.com](https://www.fluttericon.com/) creates by exposing only one super class that merges all the stuff. 

For now my problem is fixed but I leave the issue open to get other hints from the maintainer, or from you guys, on how to manage all in a better way.

**Comment by Flucadetena** [comment]
Today I had the same issue with only 24 icons. I manage to solve the problem by reducing to 20 icons, and after downloading once adding the other 4 and downloading again.

Don't really know what was happening ;)

**Comment by maerlynflagg** [comment]
i have the same issue today. i have 516, which are needed. it is a bad way to split and merge manually.

so same issue with website and same issue with the fontello-cli.

**Workaround**

upload all .svg to http://fontello.com/ or https://icomoon.io/ and download the font. then you can add the font zu flutter project. you have create manuelly the dart class. 
this is on many icons not really funny.

Please fix the issue. Or is it possible to generate the dart file locallly?

**Edit**
I tried with 20 Icons, it worked but is not a nice solution to make 25 single packages and merge them manuelly together. there can be always come new icons to the set, so every time merging.

**Comment by ilikerobots** [comment]
Hi guys.  This is only happening with custom SVG, correct?

**Comment by Flucadetena** [comment]
Hi @ilikerobots I guess so. If you mean Only using custom svg's, no. By this I mean trying to download a file with custom and icons from some sources of the app. 

But if you mean if it happens when only using icons already on the platform, I don't know.

It only happend to me when using custom yes.

If you need us to do some test or something, or even if we can help please let me know. Happy to help with this great tool.

**Comment by ilikerobots** [comment]
I've updated the site config to allow significantly larger HTTP request bodies (new limit 24m).  I was able to download 1500+ custom icons with this config.  Can someone listening on this issue also confirm?

Thanks for reporting and helping!

**Comment by Flucadetena** [comment]
Thabyou @ilikerobots this is a great tool. Essential now in my workflow. I don't have such a large set, but I'll do some testing and get back to you.

**Comment by maerlynflagg** [comment]
now the uploading and the download is working. i got my new TTF and my new DART file. but now, i have issues with the new icon dart file.

all old icon dart files and TTF files working fine. please look here #54.

**Comment by ilikerobots** [comment]
Thanks, closing.
