### ISSUE TITLE
Can not download the icons showing "Communication problems. Try again later"

### ISSUE THREAD

**Issue by BlackStriker99** [ilikerobots/fontello#50]

**Comment by BlackStriker99** [comment]
![image](https://user-images.githubusercontent.com/40071991/92104624-36335a80-edff-11ea-8391-e7373662fb3b.png)

**Comment by ilikerobots** [comment]
This may have been caused by the recent SSL certificate expiration.  Can you try again and tell me ifyour error persists?

**Comment by BlackStriker99** [comment]
> This may have been caused by the recent SSL certificate expiration. Can you try again and tell me ifyour error persists?

yes now it's working thanks @ilikerobots
