### ISSUE TITLE
Dart file issues

### ISSUE THREAD

**Issue by maerlynflagg** [ilikerobots/fontello#54]
after downloading #46 is now working, i found other issues after replacing the old TTF and old dart file.

i have do get packages again and i cleaned the flutter build. i tried to delete the old dart file and add the new one. 
the issues are only with the new downloaded dart file, not with the old icon dart files.

currently i cannot build the app.

maybe i'm missing something?

the errors:

`Expected to find ';'.`

```
IconData isn't a type.
Try correcting the name to match an existing type.
```

```
Const variables must be initialized with a constant value.
Try changing the initializer to be a constant expression.
```

to visualize you the problem , here a simple screenshot:
![icon_errors](https://user-images.githubusercontent.com/13437496/94574347-4d852c80-0273-11eb-8c78-7d83b0dd076f.jpg)

**Comment by ilikerobots** [comment]
It's likely the variable name beginning with a number, which is disallowed by Dart lang spec.  I should put in a filter to rename leading integer icon names (I thought I already had, in fact).  But for now, just rename your icon to a valid dart id, e.g. "drei_fach_verglast".

**Comment by maerlynflagg** [comment]
Thanks for help. issue solved. :)
