### ISSUE TITLE
Add String Type to _kFontPkg to avoid linter errors

### ISSUE THREAD

**Issue by mnehrig** [ilikerobots/fontello#58]
Hi,

Just a minor Suggestion:

In the generated dart file, change:
`static` const _kFontPkg = null;
to
`static` const String _kFontPkg = null;

This avoids an error with stricter lint configurations using 'implicit_dynamic_field'.

Great project! Thank u very much!

**Comment by ilikerobots** [comment]
Thank you, released.  I added null safety as well: https://github.com/ilikerobots/polyicon/commit/6bb58ee11fa860c70002c1840099acb34d3b32b2
