### ISSUE TITLE
fluttericon.com - Invalid params: - data.config is required (undefined)

### ISSUE THREAD

**Issue by xang555** [ilikerobots/fontello#69]
picked icon and click download has popup error dialog message `Invalid params: - data.config is required (undefined)` in `fluttericon.com`

**Comment by ReemNawaf** [comment]
Facing the same error.

**Comment by javaherisaber** [comment]
Same error happens to me also
I have 52 custom icons from svg and no built-in font selected

**Comment by oleksii-pimenov** [comment]
Yea, #meTo

**Comment by kunalkashyap855** [comment]
Facing the exact same error.

**Comment by JaluDwija37** [comment]
I got the same error

**Comment by RuslanBarcho** [comment]
Got the same error with 32 custom icons and no built-in one

**Comment by ajaykaju** [comment]
Facing the same.

**Comment by cnksoft** [comment]
Yes. facing the same error, even with only 1 or 2 icons. I have tried with different class names, but always the very same. Any solution?

**Comment by ilikerobots** [comment]
Repaired.  Sorry for the downtime.

**Comment by stevanusw28** [comment]
@ilikerobots is the Flutter Icon down again?

**Comment by jfushada** [comment]
same error is happening to me as well.

**Comment by ilikerobots** [comment]
Repaired.
