### ISSUE TITLE
[FR] Add ability to select all fonts in a fontset

### ISSUE THREAD

**Issue by HelgeSverre** [ilikerobots/fontello#9]
I have a use-case where I want to select all the fonts within a SVG fontset that I have uploaded, however it is only possible to select fonts one by one, this is very tedius, I would love to see a "select all" button next to the fontset name.

![image](https://user-images.githubusercontent.com/1089652/55777018-e7b14d80-5a9e-11e9-93e0-6a5769973a02.png)

**Comment by ilikerobots** [comment]
It's not quite as convenient as a select all, but it is possible to select/deselect multiple icons by drawing a box with the mouse. 

![Screenshot_fluttericon_multiselect](https://user-images.githubusercontent.com/6736189/55785732-a0858580-5abb-11e9-83d8-8a3aa9ed0aaf.png)

**Comment by deandreamatias** [comment]
It seems to me that this feature should be more evident to the user. I also thought that it was not possible to select all the icons.

**Comment by lukepighetti** [comment]
I didn't know you could select multiple icons until I saw this issue.

**Comment by hernandohhoyos** [comment]
Add this feature to the wiki so everyone knows it.

**Comment by ilikerobots** [comment]
@hernandoh : Added to wiki.

https://github.com/ilikerobots/polyicon/wiki/Selecting-multiple-icons-at-once

**Comment by ilikerobots** [comment]
I added a select all / select none in the top right corner of each family.
